### PR TITLE
Add Required interfaces

### PR DESCRIPTION
**Pull request by ryandberger**
- Fulfills [UIROLES-19](https://issues.folio.org/browse/UIROLES-19)

### CODE REVIEW

**Review by zburke — COMMENTED** [review]
These changes will read/publish a new MD whenever GH receives a new commit on any branch. That's not correct: MDs should only be published when the PR is merged. This change would make the workflow inconsistent with all other UI repos. 

What sparked you to make this change?

**Comment by ryandberger** [comment]
> These changes will read/publish a new MD whenever GH receives a new commit on any branch. That's not correct: MDs should only be published when the PR is merged. This change would make the workflow inconsistent with all other UI repos.
> 
> What sparked you to make this change?

This is a temporary change to verify that a merge to master would pass this step. Is there a preferred way to validate that is read-only?

**Comment by zburke** [comment]
@ryandberger, sorry, I just don't understand what the goal is here. By "this is just temporary" you mean you're trying to see if our build pipelines would accept this new interface requirement, and then you'll revert the change before the PR merges? OK, but that feels risky. Also, validating requirements to avoid breaking the build _is_ a worthy idea, but it's an operational concern for the nightly builds, not something this module itself needs to care about.

**Comment by ryandberger** [comment]
> @ryandberger, sorry, I just don't understand what the goal is here. By "this is just temporary" you mean you're trying to see if our build pipelines would accept this new interface requirement, and then you'll revert the change before the PR merges? OK, but that feels risky. Also, validating requirements to avoid breaking the build _is_ a worthy idea, but it's an operational concern for the nightly builds, not something this module itself needs to care about.

Good point. I will revert the build script changes.

**Comment by ryandberger** [comment]
Confirmed all required interfaces are now available in community MDR. This is ready to merge.

**Pull request merged**
